notifications:
  email: false

language: node_js
node_js:
  - 14
  - node

sudo: required

# - os: linux
#   addons:
#     apt:
#       sources:
#         - ubuntu-toolchain-r-test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

services:
  - zmq

env:
  - CC=gcc-7 CXX=g++-7



# before_install:
#   - sudo apt-get install -y ubuntu-toolchain-r-test g++-7