notifications:
  email: false

language: node_js
node_js:
  - 14

sudo: required

- os: linux
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test

services:
  - zmq

env:
  - CC=gcc-7 CXX=g++-7



# before_install:
#   - sudo apt-get install -y ubuntu-toolchain-r-test g++-7